/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef HCOM_GRADIENT_SPLIT_TUNE_H
#define HCOM_GRADIENT_SPLIT_TUNE_H

#include <string>
#include <vector>

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

/**
 * @brief the metric of profiling
 */
struct ProfilingMetric {
  std::string modelName;  /* modelName generated by GE, also known as the name of subgraph */
  std::string opName;     /* operator name, definited by TBE operator */
  std::string opType;     /* operator type, definited by TBE operator */
  uint64_t taskStartTime; /* task execution start time */
  uint64_t taskEndTime;   /* task execution end time */
};

/**
 * @brief gradient Split Tune functions return value definition
 */
typedef enum tagTuneResult {
  TUNE_SUCCESS = 0,             /* success */
  TUNE_E_PARA = 1,              /* parameter error */
  TUNE_E_PTR = 2,               /* empty pointer */
  TUNE_E_OPEN_FILE_FAILURE = 3, /* open file fail */
  TUNE_E_DATA_NOT_MATCH = 4,    /* data not match */
  TUNE_E_RESERVED               /* reserved */
} TuneResult_t;

/**
 * @brief use profiling metric to obtain gradient split tactics
 *
 * @param taskProfilingList A two-dimensional vector array identifying the profiling metric.
 * @param workPath A string identifying the path to save the gradient split tactics.
 * @return TuneResult_t
 */
TuneResult_t HcomGradientFusionTune(const std::vector<std::vector<struct ProfilingMetric>> &taskProfilingList,
                                    std::string workPath);

#ifdef __cplusplus
}
#endif  // __cplusplus
#endif  // HCOM_GRADIENT_SPLIT_TUNE_H