/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "cpp_generator.h"

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <unistd.h>

#include <gtest/gtest.h>

#include "graph/operator_reg.h"
#include "op_desc_utils.h"

using namespace ge;

namespace {
ge::es::history::Param MakeParam(const ge::es::history::ParamCxxKind kind,
                                 const ge::es::history::ParamRole role,
                                 const std::string &ir_name,
                                 const std::string &name,
                                 const bool has_default = false,
                                 const std::string &default_expr = "") {
  ge::es::history::Param param;
  param.kind = kind;
  param.role = role;
  param.ir_name = ir_name;
  param.name = name;
  param.has_default = has_default;
  param.default_expr = default_expr;
  return param;
}

void EnsureDir(const std::string &path) {
  std::string cmd = "mkdir -p " + path;
  (void)std::system(cmd.c_str());
}

void WriteFile(const std::string &path, const std::string &content) {
  std::ofstream ofs(path);
  ASSERT_TRUE(ofs.is_open());
  ofs << content;
}

void WriteSingleVersionRegistry(const std::string &registry_dir,
                                const std::string &version,
                                const std::string &date,
                                const std::string &operators_json) {
  EnsureDir(registry_dir);
  EnsureDir(registry_dir + "registry/" + version + "/");
  WriteFile(registry_dir + "index.json",
            R"({"version":"1.0.0","releases":[{"release_version":")" + version + R"(","release_date":")" + date + R"("}]})");
  WriteFile(registry_dir + "registry/" + version + "/metadata.json",
            R"({"release_version":")" + version + R"(","branch_name":"master"})");
  WriteFile(registry_dir + "registry/" + version + "/operators.json", operators_json);
}

struct RegistryVersionRecord {
  std::string version;
  std::string date;
  std::string operators_json;
};

void WriteMultiVersionRegistry(const std::string &registry_dir, const std::vector<RegistryVersionRecord> &versions) {
  ASSERT_FALSE(versions.empty());
  EnsureDir(registry_dir);
  std::stringstream index_ss;
  index_ss << R"({"version":"1.0.0","releases":[)";
  for (size_t i = 0U; i < versions.size(); ++i) {
    const auto &ver = versions[i];
    if (i != 0U) {
      index_ss << ",";
    }
    index_ss << R"({"release_version":")" << ver.version << R"(","release_date":")" << ver.date << R"("})";
    EnsureDir(registry_dir + "registry/" + ver.version + "/");
    WriteFile(registry_dir + "registry/" + ver.version + "/metadata.json",
              R"({"release_version":")" + ver.version + R"(","branch_name":"master"})");
    WriteFile(registry_dir + "registry/" + ver.version + "/operators.json", ver.operators_json);
  }
  index_ss << "]}";
  WriteFile(registry_dir + "index.json", index_ss.str());
}

auto Normalize = [](const std::string &code) {
  std::string str = code;
  str.erase(std::remove_if(str.begin(), str.end(), ::isspace), str.end());
  return str;
};

const char kExpectedGenOpKeepsSingleSignature[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i1opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i1opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_1i1opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   dx
 */
inline EsTensorHolder phony_1i1opi_1o(const EsTensorLike & x, const EsTensorLike & dx, bool flag, ge::DataType dt=ge::DT_FLOAT) {
  auto *owner_graph_builder = ResolveBuilder(x, dx);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_1i1opi_1o(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), dx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), flag, static_cast<C_DataType>(dt));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithPlanUsesOwnerBuilderFromSignatureOnly[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_3opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object or owner_builder should be provided:
 *   x1
 *   x2
 *   x3
 */
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1=nullptr, const EsTensorLike & x2, const EsTensorLike & x3=nullptr) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, x3);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x3.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), owner_graph_builder == nullptr ? nullptr : owner_graph_builder->GetCGraphBuilder());
  return out;
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithPlanUsesSignatureNamesForDynamicOutputAndSubgraph[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_Case_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_Case_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_phony_Case_c.h"
namespace ge {
namespace es {

/**
 * @note lifecycles of following subgraph inputs will be transferred to the EsCGraphBuilder:
 *   branches
 * @note user needs to provide following inputs for dynamic output numbers:
 *   output_num: dynamic output number of output
 */
inline std::vector<EsTensorHolder> phony_Case(const EsTensorHolder & branch_index, const std::vector<EsTensorHolder> & input, int64_t my_output_num, std::vector<std::unique_ptr<ge::Graph>> my_branches) {
  auto esb_input = TensorsToEsCTensorHolders(input);
  auto esb_my_branches= static_cast<int64_t>(my_branches.size());
  auto out = Esphony_Case(branch_index.GetCTensorHolder(), esb_input.data(), static_cast<int64_t>(esb_input.size()), my_output_num, GeGraphsToEsCGraphs(std::move(my_branches)).data(), esb_my_branches);
  std::vector<EsTensorHolder> output_dynamic_outs;
  output_dynamic_outs.reserve(out.output_num);
  for (int64_t dyn_idx = 0; dyn_idx < out.output_num; ++dyn_idx) {
    output_dynamic_outs.emplace_back(out.output[dyn_idx]);
  }
  return {output_dynamic_outs};
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithDuplicateInputAndAttrNamesPassesAttrParams[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_dup_name_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_dup_name_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_dup_name_c.h"
namespace ge {
namespace es {

struct phony_dup_nameOutput {
  std::vector<EsTensorHolder> ref_x;
  std::vector<EsTensorHolder> ref_dx;
};
/**
 * @note lifecycles of following tensor attribute inputs will be transferred to the EsCGraphBuilder:
 *   value
 * @note user needs to provide following inputs for dynamic output numbers:
 *   ref_x_num: dynamic output number of x
 *   ref_dx_num: dynamic output number of dx
 */
inline phony_dup_nameOutput phony_dup_name(const EsTensorLike & x, const std::vector<EsTensorHolder> & dx, int64_t ref_x_num, int64_t ref_dx_num, int64_t index=0, std::unique_ptr<ge::Tensor> value=EsMakeUnique<ge::Tensor>(ge::Tensor()), int64_t attr_x=1, int64_t attr_dx=2) {
  auto *owner_graph_builder = ResolveBuilder(x, dx);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_dx = TensorsToEsCTensorHolders(dx);
  auto out = Esphony_dup_name(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), esb_dx.data(), static_cast<int64_t>(esb_dx.size()), ref_x_num, ref_dx_num, index, static_cast<EsCTensor *>(static_cast<void *>(value.release())), attr_x, attr_dx);
  std::vector<EsTensorHolder> ref_x_dynamic_outs;
  ref_x_dynamic_outs.reserve(out.ref_x_num);
  for (int64_t dyn_idx = 0; dyn_idx < out.ref_x_num; ++dyn_idx) {
    ref_x_dynamic_outs.emplace_back(out.ref_x[dyn_idx]);
  }
  std::vector<EsTensorHolder> ref_dx_dynamic_outs;
  ref_dx_dynamic_outs.reserve(out.ref_dx_num);
  for (int64_t dyn_idx = 0; dyn_idx < out.ref_dx_num; ++dyn_idx) {
    ref_dx_dynamic_outs.emplace_back(out.ref_dx[dyn_idx]);
  }
  return {ref_x_dynamic_outs, ref_dx_dynamic_outs};
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithPlanMissingDynamicOutputParamGeneratesDeletedOverload[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_Case_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_Case_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_phony_Case_c.h"
namespace ge {
namespace es {

/**
 * @note lifecycles of following subgraph inputs will be transferred to the EsCGraphBuilder:
 *   branches
 * @note user needs to provide following inputs for dynamic output numbers:
 *   output_num: dynamic output number of output
 */
/**
 * @warning cpp_generator: op phony_Case missing dynamic_output_num params for [output], emit deleted overload
 */
[[deprecated("Invalid overload signature blocked: missing dynamic_output_num params for [output]")]] inline std::vector<EsTensorHolder> phony_Case(const EsTensorHolder & branch_index, const std::vector<EsTensorHolder> & input, std::vector<std::unique_ptr<ge::Graph>> branches) = delete;
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithPlanMissingSubgraphParamGeneratesDeletedOverload[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_Case_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_Case_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_phony_Case_c.h"
namespace ge {
namespace es {

/**
 * @note lifecycles of following subgraph inputs will be transferred to the EsCGraphBuilder:
 *   branches
 * @note user needs to provide following inputs for dynamic output numbers:
 *   output_num: dynamic output number of output
 */
/**
 * @warning cpp_generator: op phony_Case missing subgraph params for [branches], emit deleted overload
 */
[[deprecated("Invalid overload signature blocked: missing subgraph params for [branches]")]] inline std::vector<EsTensorHolder> phony_Case(const EsTensorHolder & branch_index, const std::vector<EsTensorHolder> & input, int64_t output_num) = delete;
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithHistoryRegistryGeneratesOverloadsForAllOptionalInputs[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_3opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object or owner_builder should be provided:
 *   x1
 *   x2
 *   x3
 */
/**
 * @warning Context: op phony_3opi_1o, new optional inputs [x3]. Action: Try0 overloads (legacy + full signature) are ambiguous, so switch to A1: force new inputs required and add nullptr-guard overloads.
 * @warning Context: op phony_3opi_1o, new optional inputs [x3]. Action: A1 overloads are still ambiguous, so switch to A2: force new inputs as TensorHolder and add nullptr-guard overloads.
 */
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1=nullptr, const EsTensorLike & x2=nullptr, const EsGraphBuilder * owner_builder=nullptr) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, owner_builder);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), nullptr, owner_builder == nullptr ? nullptr : owner_builder->GetCGraphBuilder());
  return out;
}
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1, const EsTensorLike & x2, const EsTensorHolder & x3) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, x3);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x3.GetCTensorHolder(), owner_graph_builder == nullptr ? nullptr : owner_graph_builder->GetCGraphBuilder());
  return out;
}
[[deprecated("New input x3 uses TensorHolder for disambiguation. Use legacy overload when disconnected, or use CreateScalar/CreateVector/CreateConst for constants.")]] inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1, const EsTensorLike & x2, std::nullptr_t x3) = delete;
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithHistoryRegistryAttrOnlyChangeKeepsSingleSignature[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_phony_1i_1o_c.h"
namespace ge {
namespace es {

inline EsTensorHolder phony_1i_1o(const EsTensorHolder & x, int64_t index=0) {
  auto out = Esphony_1i_1o(x.GetCTensorHolder(), index);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithHistoryRegistryMultiVersionA2GeneratesTensorHolderAndGuards[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_3opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object or owner_builder should be provided:
 *   x1
 *   x2
 *   x3
 */
/**
 * @warning Context: op phony_3opi_1o, new optional inputs [x2, x3]. Action: Try0 overloads (legacy + full signature) are ambiguous, so switch to A1: force new inputs required and add nullptr-guard overloads.
 * @warning Context: op phony_3opi_1o, new optional inputs [x2, x3]. Action: A1 overloads are still ambiguous, so switch to A2: force new inputs as TensorHolder and add nullptr-guard overloads.
 */
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1=nullptr, const EsGraphBuilder * owner_builder=nullptr) {
  auto *owner_graph_builder = ResolveBuilder(x1, owner_builder);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), nullptr, nullptr, owner_builder == nullptr ? nullptr : owner_builder->GetCGraphBuilder());
  return out;
}
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1, const EsTensorHolder & x2) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.GetCTensorHolder(), nullptr, owner_graph_builder == nullptr ? nullptr : owner_graph_builder->GetCGraphBuilder());
  return out;
}
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1, const EsTensorHolder & x2, const EsTensorHolder & x3) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, x3);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.GetCTensorHolder(), x3.GetCTensorHolder(), owner_graph_builder == nullptr ? nullptr : owner_graph_builder->GetCGraphBuilder());
  return out;
}
[[deprecated("New input x2 uses TensorHolder for disambiguation. Use legacy overload when disconnected, or use CreateScalar/CreateVector/CreateConst for constants.")]] inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1, std::nullptr_t x2) = delete;
[[deprecated("New input x3 uses TensorHolder for disambiguation. Use legacy overload when disconnected, or use CreateScalar/CreateVector/CreateConst for constants.")]] inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1, const EsTensorHolder & x2, std::nullptr_t x3) = delete;
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithHistoryRegistryIncompatibleMiddleVersionFallsBackToA0[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_3opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_3opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object or owner_builder should be provided:
 *   x1
 *   x2
 *   x3
 */
/**
 * @warning Context: op phony_3opi_1o. Cause: incompatible schema change in history chain at step 1: input mismatch at index 0. Action: fall back to A0 single-signature plan to avoid ambiguous or incompatible overloads.
 */
inline EsTensorHolder phony_3opi_1o(const EsTensorLike & x1=nullptr, const EsTensorLike & x2=nullptr, const EsTensorLike & x3=nullptr, const EsGraphBuilder * owner_builder=nullptr) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, x3, owner_builder);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_3opi_1o(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x3.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), owner_builder == nullptr ? nullptr : owner_builder->GetCGraphBuilder());
  return out;
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithHistoryRegistryScenarioAOnlyNewOptionalInputNoScalarLiteralAmbiguity[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i1opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i1opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_1i1opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   dx
 */
inline EsTensorHolder phony_1i1opi_1o(const EsTensorLike & x, bool flag, ge::DataType dt=ge::DT_FLOAT) {
  auto *owner_graph_builder = ResolveBuilder(x);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_1i1opi_1o(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), nullptr, flag, static_cast<C_DataType>(dt));
  return out;
}
inline EsTensorHolder phony_1i1opi_1o(const EsTensorLike & x, const EsTensorLike & dx, bool flag, ge::DataType dt=ge::DT_FLOAT) {
  auto *owner_graph_builder = ResolveBuilder(x, dx);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_1i1opi_1o(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), dx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), flag, static_cast<C_DataType>(dt));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
)";

const char kExpectedGenOpWithHistoryRegistryScenarioCDeleteRequiredInputFallsBackToA0[] = R"(
/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i1opi_1o_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_phony_1i1opi_1o_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_phony_1i1opi_1o_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   dx
 */
/**
 * @warning Context: op phony_1i1opi_1o. Cause: incompatible schema change in history chain at step 1: inputs shrink from 3 to 2. Action: fall back to A0 single-signature plan to avoid ambiguous or incompatible overloads.
 */
inline EsTensorHolder phony_1i1opi_1o(const EsTensorLike & x, const EsTensorLike & dx, bool flag, ge::DataType dt=ge::DT_FLOAT) {
  auto *owner_graph_builder = ResolveBuilder(x, dx);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = Esphony_1i1opi_1o(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), dx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), flag, static_cast<C_DataType>(dt));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
)";

} // namespace
class CppGeneratorOverloadTest : public ::testing::Test {
  protected:
    void SetUp() override {
      generator_ = std::make_unique<es::CppGenerator>();
    }

    void TearDown() override {
      for (const auto &dir : temp_dirs_) {
        (void)std::system(("rm -rf " + dir).c_str());
      }
      generator_.reset();
    }

    std::string CreateTempRegistryDir(const std::string &tag) {
      static size_t seq = 0U;
      std::string dir = "./cpp_generator_overload_registry_" + tag + "_" + std::to_string(getpid()) +
                        "_" + std::to_string(seq++) + "/";
      temp_dirs_.emplace_back(dir);
      return dir;
    }

    std::unique_ptr<es::CppGenerator> generator_;
    std::vector<std::string> temp_dirs_;
};
TEST_F(CppGeneratorOverloadTest, GenOpKeepsSingleSignature) {
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_1i1opi_1o", "phony_1i1opi_1o"));
  generator_->GenOp(op_desc);
  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_1i1opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpKeepsSingleSignature;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithPlanUsesOwnerBuilderFromSignatureOnly) {
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_3opi_1o", "phony_3opi_1o"));
  generator_->GenOp(op_desc);
  ge::es::history::OverloadPlan plan;
  ge::es::history::Signature sig;
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kEsTensorLikeRef,
                                    ge::es::history::ParamRole::kInput,
                                    "x1",
                                    "x1",
                                    true,
                                    "=nullptr"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kEsTensorLikeRef,
                                    ge::es::history::ParamRole::kInput,
                                    "x2",
                                    "x2",
                                    false));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kEsTensorLikeRef,
                                    ge::es::history::ParamRole::kInput,
                                    "x3",
                                    "x3",
                                    true,
                                    "=nullptr"));
  plan.signatures.emplace_back(sig);

  std::vector<std::string> warnings;
  generator_->GenOpWithPlan(op_desc, plan, warnings);
  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_3opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithPlanUsesOwnerBuilderFromSignatureOnly;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithPlanUsesSignatureNamesForDynamicOutputAndSubgraph) {
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_Case", "phony_Case"));
  generator_->GenOp(op_desc);
  ge::es::history::OverloadPlan plan;
  ge::es::history::Signature sig;
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kTensorHolderRef,
                                    ge::es::history::ParamRole::kInput,
                                    "branch_index",
                                    "branch_index"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kTensorHoldersVecRef,
                                    ge::es::history::ParamRole::kInput,
                                    "input",
                                    "input"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kInt64,
                                    ge::es::history::ParamRole::kDynamicOutputNum,
                                    "output",
                                    "my_output_num"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kGraphsVec,
                                    ge::es::history::ParamRole::kSubgraph,
                                    "branches",
                                    "my_branches"));
  plan.signatures.emplace_back(sig);

  std::vector<std::string> warnings;
  generator_->GenOpWithPlan(op_desc, plan, warnings);
  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_Case");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithPlanUsesSignatureNamesForDynamicOutputAndSubgraph;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithDuplicateInputAndAttrNamesPassesAttrParams) {
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_dup_name", "phony_dup_name"));
  generator_->GenOp(op_desc);
  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_dup_name");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithDuplicateInputAndAttrNamesPassesAttrParams;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithPlanMissingDynamicOutputParamGeneratesDeletedOverload) {
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_Case", "phony_Case"));
  ge::es::history::OverloadPlan plan;
  ge::es::history::Signature sig;
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kTensorHolderRef,
                                    ge::es::history::ParamRole::kInput,
                                    "branch_index",
                                    "branch_index"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kTensorHoldersVecRef,
                                    ge::es::history::ParamRole::kInput,
                                    "input",
                                    "input"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kGraphsVec,
                                    ge::es::history::ParamRole::kSubgraph,
                                    "branches",
                                    "branches"));
  plan.signatures.emplace_back(sig);

  std::vector<std::string> warnings;
  generator_->GenOpWithPlan(op_desc, plan, warnings);
  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_Case");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithPlanMissingDynamicOutputParamGeneratesDeletedOverload;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
  ASSERT_FALSE(warnings.empty());
  const std::string expected_warning =
      "cpp_generator: op phony_Case missing dynamic_output_num params for [output], emit deleted overload";
  EXPECT_EQ(warnings.back(), expected_warning);
}

TEST_F(CppGeneratorOverloadTest, GenOpWithPlanMissingSubgraphParamGeneratesDeletedOverload) {
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_Case", "phony_Case"));
  ge::es::history::OverloadPlan plan;
  ge::es::history::Signature sig;
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kTensorHolderRef,
                                    ge::es::history::ParamRole::kInput,
                                    "branch_index",
                                    "branch_index"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kTensorHoldersVecRef,
                                    ge::es::history::ParamRole::kInput,
                                    "input",
                                    "input"));
  sig.params.emplace_back(MakeParam(ge::es::history::ParamCxxKind::kInt64,
                                    ge::es::history::ParamRole::kDynamicOutputNum,
                                    "output",
                                    "output_num"));
  plan.signatures.emplace_back(sig);

  std::vector<std::string> warnings;
  generator_->GenOpWithPlan(op_desc, plan, warnings);
  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_Case");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithPlanMissingSubgraphParamGeneratesDeletedOverload;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
  ASSERT_FALSE(warnings.empty());
  const std::string expected_warning =
      "cpp_generator: op phony_Case missing subgraph params for [branches], emit deleted overload";
  EXPECT_EQ(warnings.back(), expected_warning);
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryGeneratesOverloadsForAllOptionalInputs) {
  const std::string registry_dir = CreateTempRegistryDir("phony_3opi_1o");
  WriteSingleVersionRegistry(
    registry_dir,
    "9.0.RC1",
    "2025-01-01",
    R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"},{"name":"x2","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})");

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC1");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_3opi_1o", "phony_3opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_3opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryGeneratesOverloadsForAllOptionalInputs;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryAttrOnlyChangeKeepsSingleSignature) {
  const std::string registry_dir = CreateTempRegistryDir("phony_1i_1o");
  WriteSingleVersionRegistry(
    registry_dir,
    "9.0.RC1",
    "2025-01-01",
    R"({"operators":[{"op_type":"phony_1i_1o","inputs":[{"name":"x","type":"INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})");

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC1");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_1i_1o", "phony_1i_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_1i_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryAttrOnlyChangeKeepsSingleSignature;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryMultiVersionA0KeepsSingleSignature) {
  const std::string registry_dir = CreateTempRegistryDir("phony_1i_1o_multiversion_a0");
  WriteMultiVersionRegistry(
    registry_dir,
    {
      {"9.0.RC1",
       "2025-01-01",
       R"({"operators":[{"op_type":"phony_1i_1o","inputs":[{"name":"x","type":"INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"},
      {"9.0.RC2",
       "2025-06-01",
       R"({"operators":[{"op_type":"phony_1i_1o","inputs":[{"name":"x","type":"INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[{"name":"index","type":"Int","required":false,"default_value":"0"}],"subgraphs":[]}]})"}
    });

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC2");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_1i_1o", "phony_1i_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_1i_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryAttrOnlyChangeKeepsSingleSignature;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryMultiVersionA1GeneratesLegacyAndFullSignatures) {
  const std::string registry_dir = CreateTempRegistryDir("phony_3opi_1o_multiversion_a1");
  WriteMultiVersionRegistry(
    registry_dir,
    {
      {"9.0.RC1",
       "2025-01-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"},{"name":"x2","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"},
      {"9.0.RC2",
       "2025-06-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"},{"name":"x2","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"}
    });

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC2");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_3opi_1o", "phony_3opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_3opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryGeneratesOverloadsForAllOptionalInputs;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryMultiVersionA2GeneratesTensorHolderAndGuards) {
  const std::string registry_dir = CreateTempRegistryDir("phony_3opi_1o_multiversion_a1");
  WriteMultiVersionRegistry(
    registry_dir,
    {
      {"9.0.RC1",
       "2025-01-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"},
      {"9.0.RC2",
       "2025-06-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"},{"name":"x2","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"}
    });

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC2");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_3opi_1o", "phony_3opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_3opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryMultiVersionA2GeneratesTensorHolderAndGuards;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryIncompatibleMiddleVersionFallsBackToA0) {
  const std::string registry_dir = CreateTempRegistryDir("phony_3opi_1o_fallback_a0");
  WriteMultiVersionRegistry(
    registry_dir,
    {
      {"9.0.RC1",
       "2025-01-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"},
      {"9.0.RC2",
       "2025-06-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"z1","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"}
    });

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC2");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_3opi_1o", "phony_3opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_3opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryIncompatibleMiddleVersionFallsBackToA0;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryScenarioAOnlyNewOptionalInputNoScalarLiteralAmbiguity) {
  // 场景A（现有原型近似）：
  // 使用 phony_1i1opi_1o，历史版本无 dx，当前版本新增可选输入 dx。
  // 该原型含 required attr(flag)，因此不会引入标量字面量二义性，期望生成 legacy + full 两个重载。
  const std::string registry_dir = CreateTempRegistryDir("scenario_a_existing_proto");
  WriteSingleVersionRegistry(
    registry_dir,
    "9.0.RC1",
    "2025-01-01",
    R"({"operators":[{"op_type":"phony_1i1opi_1o","inputs":[{"name":"x","type":"INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[{"name":"dt","type":"Type","required":false,"default_value":"\"DT_FLOAT\""},{"name":"flag","type":"Bool","required":true}],"subgraphs":[]}]})");

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC1");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_1i1opi_1o", "phony_1i1opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_1i1opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content =
      kExpectedGenOpWithHistoryRegistryScenarioAOnlyNewOptionalInputNoScalarLiteralAmbiguity;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryScenarioBNewOptionalInputAndA2TensorHolderDisambiguation) {
  // 场景B（现有原型可表达的 A2 形态）：
  // 新增可选输入后触发 A2，新增输入改为 TensorHolder 并生成 nullptr 防呆重载。
  const std::string registry_dir = CreateTempRegistryDir("scenario_b_existing_proto_a2");
  WriteMultiVersionRegistry(
    registry_dir,
    {
      {"9.0.RC1",
       "2025-01-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"},
      {"9.0.RC2",
       "2025-06-01",
       R"({"operators":[{"op_type":"phony_3opi_1o","inputs":[{"name":"x1","type":"OPTIONAL_INPUT"},{"name":"x2","type":"OPTIONAL_INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[],"subgraphs":[]}]})"}
    });

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC2");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_3opi_1o", "phony_3opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_3opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryMultiVersionA2GeneratesTensorHolderAndGuards;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}

TEST_F(CppGeneratorOverloadTest, GenOpWithHistoryRegistryScenarioCDeleteRequiredInputFallsBackToA0) {
  // 场景C：
  // 历史版本包含额外必选输入 z，当前版本删除该必选输入，判定为不兼容，回退 A0 单签名。
  const std::string registry_dir = CreateTempRegistryDir("scenario_c_delete_required_input");
  WriteSingleVersionRegistry(
    registry_dir,
    "9.0.RC1",
    "2025-01-01",
    R"({"operators":[{"op_type":"phony_1i1opi_1o","inputs":[{"name":"x","type":"INPUT"},{"name":"dx","type":"OPTIONAL_INPUT"},{"name":"z","type":"INPUT"}],"outputs":[{"name":"y","type":"OUTPUT"}],"attrs":[{"name":"dt","type":"Type","required":false,"default_value":"\"DT_FLOAT\""},{"name":"flag","type":"Bool","required":true}],"subgraphs":[]}]})");

  generator_->SetHistoryRegistry(registry_dir);
  generator_->SetReleaseVersion("9.0.RC1");
  auto op_desc = OpDescUtils::GetOpDescFromOperator(
    ge::OperatorFactory::CreateOperator("phony_1i1opi_1o", "phony_1i1opi_1o"));
  generator_->GenOp(op_desc);

  const auto &per_ops = generator_->GetPerOpContents();
  auto it = per_ops.find("phony_1i1opi_1o");
  ASSERT_NE(it, per_ops.end());
  const std::string content = it->second.str();
  const std::string expected_cpp_content = kExpectedGenOpWithHistoryRegistryScenarioCDeleteRequiredInputFallsBackToA0;
  EXPECT_EQ(Normalize(content), Normalize(expected_cpp_content));
}
