# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of 
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

if (BUILD_OPEN_PROJECT OR ENABLE_OPEN_SRC)
    if(DEFINED BUILD_COMPONENT)
        message(STATUS "find third party packages in divided mode, component:${BUILD_COMPONENT}")
        if(BUILD_COMPONENT STREQUAL "ge-compiler")
            find_package(json MODULE REQUIRED)
            find_package(openssl MODULE REQUIRED)
            find_package(protoc MODULE REQUIRED)
            find_package(zlib MODULE REQUIRED)
            find_package(ascend_protobuf_shared MODULE REQUIRED)
            find_package(SymEngine CONFIG REQUIRED)
        elseif(BUILD_COMPONENT STREQUAL "ge-executor")
            find_package(json MODULE REQUIRED)
            find_package(protoc MODULE REQUIRED)
            find_package(protoc_grpc MODULE REQUIRED)
            find_package(protobuf_grpc MODULE REQUIRED)
            find_package(ascend_protobuf_shared MODULE REQUIRED)
            find_package(ascend_protobuf_static MODULE REQUIRED)
            find_package(zlib MODULE REQUIRED)
            find_package(gRPC CONFIG REQUIRED)
            find_package(SymEngine CONFIG REQUIRED)
            find_package(Boost CONFIG REQUIRED)
        else()
            find_package(Threads)
            find_package(json MODULE REQUIRED)
            find_package(openssl MODULE REQUIRED)
            find_package(protoc MODULE REQUIRED)
            find_package(protoc_grpc MODULE REQUIRED)
            find_package(protobuf_grpc MODULE REQUIRED)
            find_package(protobuf_static MODULE REQUIRED)
            find_package(ascend_protobuf_shared MODULE REQUIRED)
            find_package(ascend_protobuf_static MODULE REQUIRED)
            find_package(zlib MODULE REQUIRED)
            find_package(gRPC CONFIG REQUIRED)
            find_package(SymEngine CONFIG REQUIRED)
            find_package(Boost CONFIG REQUIRED)
        endif()
    else()
        message(STATUS "find third party packages in normal mode")
        find_package(Threads)
        find_package(json MODULE REQUIRED)
        find_package(openssl MODULE REQUIRED)
        find_package(zlib MODULE REQUIRED)
        find_package(protoc MODULE REQUIRED)
        find_package(protoc_grpc MODULE REQUIRED)
        find_package(protobuf_grpc MODULE REQUIRED)
        find_package(protobuf_static MODULE REQUIRED)
        find_package(ascend_protobuf_shared MODULE REQUIRED)
        find_package(ascend_protobuf_static MODULE REQUIRED)
        find_package(gRPC CONFIG REQUIRED)
        find_package(SymEngine CONFIG REQUIRED)
        find_package(Boost CONFIG REQUIRED)
    endif()
endif ()
